version: 0.0
os: linux
files:
  - source: /docker-compose.yaml
    destination: /home/ubuntu/my-python-app
    permissions:
      - object: /home/ubuntu/my-python-app
        pattern: "**"
        owner: ubuntu
        group: ubuntu
        mode: 755

hooks:
  BeforeInstall:
    - location: before_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: start_server.sh
      timeout: 300
      runas: root
