version: 0.0
os: linux
files:
  - source: scripts/
    destination: /home/ec2-user/deployment-scripts
hooks:
  BeforeInstall:
    - location: deployment-scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: deployment-scripts/start_server.sh
      timeout: 300
      runas: root
