version: 0.2
phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo "Preparing for Docker build..."
      - $(aws ecr get-login --region us-east-1 --no-include-email)
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t my-python-app .
      - docker tag my-python-app:latest 577638362176.dkr.ecr.us-east-2.amazonaws.com/my-python-app:latest
  post_build:
    commands:
      - echo "Pushing Docker image..."
      - docker push 577638362176.dkr.ecr.us-east-2.amazonaws.com/my-python-app:latest
