version: 0.2

# Environment variables (optional)
env:
  variables:
    APP_ENV: "production"

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo Running pre-build commands...
      - echo Checking Python version...
      - python --version

  build:
    commands:
      - echo Running build phase...
      - echo Running tests...
      - pytest

  post_build:
    commands:
      - echo Build completed on `date`.

artifacts:
  files:
    - "**/*"
  discard-paths: yes
